spring.application.name=tramplin
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/tramplin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Run data.sql after Hibernate has created/updated the schema
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
app.cache.opportunity-ttl-minutes=${CACHE_OPPORTUNITY_TTL_MINUTES:10}

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# S3
app.s3.region=${AWS_REGION}
app.s3.bucket=${S3_BUCKET}
app.s3.endpoint=${S3_ENDPOINT}
app.s3.public-base-url=${S3_ENDPOINT}/${S3_BUCKET}
app.s3.force-path-style=${S3_FORCE_PATH_STYLE:true}
app.s3.access-key=${S3_ACCESS_KEY}
app.s3.secret-key=${S3_SECRET_KEY}

# Mail
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT:465}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE:true}
spring.mail.properties.mail.smtp.ssl.enable=${MAIL_SMTP_SSL_ENABLE:false}

# Verification
# app.base-url=${APP_BASE_URL:https://tramplin-itplanet.ru}
app.base-url=${APP_BASE_URL:http://localhost:8080}
app.verification.token-ttl-hours=${VERIFICATION_TOKEN_TTL_HOURS:24}
